/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.amodel.ui.internal.AmodelActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AsomemodelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AmodelActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AmodelActivator.getInstance().getInjector(AmodelActivator.ORG_XTEXT_ASOMEMODEL);
	}
	
}
