/**
 * generated by Xtext 2.10.0
 */
package org.xtext.asomemodel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.asomemodel.AsomemodelFactory
 * @model kind="package"
 * @generated
 */
public interface AsomemodelPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "asomemodel";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/Asomemodel";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "asomemodel";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AsomemodelPackage eINSTANCE = org.xtext.asomemodel.impl.AsomemodelPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.asomemodel.impl.AsomemodelImpl <em>Asomemodel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.asomemodel.impl.AsomemodelImpl
   * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getAsomemodel()
   * @generated
   */
  int ASOMEMODEL = 0;

  /**
   * The number of structural features of the '<em>Asomemodel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASOMEMODEL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.asomemodel.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.asomemodel.impl.ModelImpl
   * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getModel()
   * @generated
   */
  int MODEL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = ASOMEMODEL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Repositoryservice</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__REPOSITORYSERVICE = ASOMEMODEL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Domaininterface</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DOMAININTERFACE = ASOMEMODEL_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = ASOMEMODEL_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.asomemodel.impl.RepositoryServiceImpl <em>Repository Service</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.asomemodel.impl.RepositoryServiceImpl
   * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getRepositoryService()
   * @generated
   */
  int REPOSITORY_SERVICE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPOSITORY_SERVICE__NAME = 0;

  /**
   * The feature id for the '<em><b>Dataport</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPOSITORY_SERVICE__DATAPORT = 1;

  /**
   * The number of structural features of the '<em>Repository Service</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPOSITORY_SERVICE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.asomemodel.impl.DomainInterfaceImpl <em>Domain Interface</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.asomemodel.impl.DomainInterfaceImpl
   * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getDomainInterface()
   * @generated
   */
  int DOMAIN_INTERFACE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_INTERFACE__NAME = 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_INTERFACE__ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Domain Interface</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_INTERFACE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.asomemodel.impl.DataPortImpl <em>Data Port</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.asomemodel.impl.DataPortImpl
   * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getDataPort()
   * @generated
   */
  int DATA_PORT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_PORT__NAME = 0;

  /**
   * The feature id for the '<em><b>Cross Model</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_PORT__CROSS_MODEL = 1;

  /**
   * The feature id for the '<em><b>Cross Interface</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_PORT__CROSS_INTERFACE = 2;

  /**
   * The number of structural features of the '<em>Data Port</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_PORT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.asomemodel.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.asomemodel.impl.ElementImpl
   * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Attri</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__ATTRI = 1;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.asomemodel.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.asomemodel.impl.EntityImpl
   * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Attri</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__ATTRI = ELEMENT__ATTRI;

  /**
   * The feature id for the '<em><b>Multiplicity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__MULTIPLICITY = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.asomemodel.impl.MultiplicityImpl <em>Multiplicity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.asomemodel.impl.MultiplicityImpl
   * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getMultiplicity()
   * @generated
   */
  int MULTIPLICITY = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICITY__NAME = 0;

  /**
   * The number of structural features of the '<em>Multiplicity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICITY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.asomemodel.impl.ValueObjectImpl <em>Value Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.asomemodel.impl.ValueObjectImpl
   * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getValueObject()
   * @generated
   */
  int VALUE_OBJECT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_OBJECT__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Attri</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_OBJECT__ATTRI = ELEMENT__ATTRI;

  /**
   * The number of structural features of the '<em>Value Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_OBJECT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.asomemodel.impl.AttriImpl <em>Attri</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.asomemodel.impl.AttriImpl
   * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getAttri()
   * @generated
   */
  int ATTRI = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRI__NAME = 0;

  /**
   * The feature id for the '<em><b>Cross Model</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRI__CROSS_MODEL = 1;

  /**
   * The feature id for the '<em><b>Cross Interface</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRI__CROSS_INTERFACE = 2;

  /**
   * The feature id for the '<em><b>Datatype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRI__DATATYPE = 3;

  /**
   * The feature id for the '<em><b>Multiplicity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRI__MULTIPLICITY = 4;

  /**
   * The feature id for the '<em><b>Order</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRI__ORDER = 5;

  /**
   * The number of structural features of the '<em>Attri</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRI_FEATURE_COUNT = 6;


  /**
   * Returns the meta object for class '{@link org.xtext.asomemodel.Asomemodel <em>Asomemodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asomemodel</em>'.
   * @see org.xtext.asomemodel.Asomemodel
   * @generated
   */
  EClass getAsomemodel();

  /**
   * Returns the meta object for class '{@link org.xtext.asomemodel.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.asomemodel.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.asomemodel.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.asomemodel.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.asomemodel.Model#getRepositoryservice <em>Repositoryservice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Repositoryservice</em>'.
   * @see org.xtext.asomemodel.Model#getRepositoryservice()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Repositoryservice();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.asomemodel.Model#getDomaininterface <em>Domaininterface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Domaininterface</em>'.
   * @see org.xtext.asomemodel.Model#getDomaininterface()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Domaininterface();

  /**
   * Returns the meta object for class '{@link org.xtext.asomemodel.RepositoryService <em>Repository Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Repository Service</em>'.
   * @see org.xtext.asomemodel.RepositoryService
   * @generated
   */
  EClass getRepositoryService();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.asomemodel.RepositoryService#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.asomemodel.RepositoryService#getName()
   * @see #getRepositoryService()
   * @generated
   */
  EAttribute getRepositoryService_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.asomemodel.RepositoryService#getDataport <em>Dataport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dataport</em>'.
   * @see org.xtext.asomemodel.RepositoryService#getDataport()
   * @see #getRepositoryService()
   * @generated
   */
  EReference getRepositoryService_Dataport();

  /**
   * Returns the meta object for class '{@link org.xtext.asomemodel.DomainInterface <em>Domain Interface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domain Interface</em>'.
   * @see org.xtext.asomemodel.DomainInterface
   * @generated
   */
  EClass getDomainInterface();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.asomemodel.DomainInterface#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.asomemodel.DomainInterface#getName()
   * @see #getDomainInterface()
   * @generated
   */
  EAttribute getDomainInterface_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.asomemodel.DomainInterface#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element</em>'.
   * @see org.xtext.asomemodel.DomainInterface#getElement()
   * @see #getDomainInterface()
   * @generated
   */
  EReference getDomainInterface_Element();

  /**
   * Returns the meta object for class '{@link org.xtext.asomemodel.DataPort <em>Data Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Port</em>'.
   * @see org.xtext.asomemodel.DataPort
   * @generated
   */
  EClass getDataPort();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.asomemodel.DataPort#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.asomemodel.DataPort#getName()
   * @see #getDataPort()
   * @generated
   */
  EAttribute getDataPort_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.asomemodel.DataPort#getCrossModel <em>Cross Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Cross Model</em>'.
   * @see org.xtext.asomemodel.DataPort#getCrossModel()
   * @see #getDataPort()
   * @generated
   */
  EReference getDataPort_CrossModel();

  /**
   * Returns the meta object for the reference '{@link org.xtext.asomemodel.DataPort#getCrossInterface <em>Cross Interface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Cross Interface</em>'.
   * @see org.xtext.asomemodel.DataPort#getCrossInterface()
   * @see #getDataPort()
   * @generated
   */
  EReference getDataPort_CrossInterface();

  /**
   * Returns the meta object for class '{@link org.xtext.asomemodel.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.asomemodel.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.asomemodel.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.asomemodel.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.asomemodel.Element#getAttri <em>Attri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attri</em>'.
   * @see org.xtext.asomemodel.Element#getAttri()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Attri();

  /**
   * Returns the meta object for class '{@link org.xtext.asomemodel.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.xtext.asomemodel.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.asomemodel.Entity#getMultiplicity <em>Multiplicity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Multiplicity</em>'.
   * @see org.xtext.asomemodel.Entity#getMultiplicity()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Multiplicity();

  /**
   * Returns the meta object for class '{@link org.xtext.asomemodel.Multiplicity <em>Multiplicity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplicity</em>'.
   * @see org.xtext.asomemodel.Multiplicity
   * @generated
   */
  EClass getMultiplicity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.asomemodel.Multiplicity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.asomemodel.Multiplicity#getName()
   * @see #getMultiplicity()
   * @generated
   */
  EAttribute getMultiplicity_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.asomemodel.ValueObject <em>Value Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value Object</em>'.
   * @see org.xtext.asomemodel.ValueObject
   * @generated
   */
  EClass getValueObject();

  /**
   * Returns the meta object for class '{@link org.xtext.asomemodel.Attri <em>Attri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attri</em>'.
   * @see org.xtext.asomemodel.Attri
   * @generated
   */
  EClass getAttri();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.asomemodel.Attri#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.asomemodel.Attri#getName()
   * @see #getAttri()
   * @generated
   */
  EAttribute getAttri_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.asomemodel.Attri#getCrossModel <em>Cross Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Cross Model</em>'.
   * @see org.xtext.asomemodel.Attri#getCrossModel()
   * @see #getAttri()
   * @generated
   */
  EReference getAttri_CrossModel();

  /**
   * Returns the meta object for the reference '{@link org.xtext.asomemodel.Attri#getCrossInterface <em>Cross Interface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Cross Interface</em>'.
   * @see org.xtext.asomemodel.Attri#getCrossInterface()
   * @see #getAttri()
   * @generated
   */
  EReference getAttri_CrossInterface();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.asomemodel.Attri#getDatatype <em>Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Datatype</em>'.
   * @see org.xtext.asomemodel.Attri#getDatatype()
   * @see #getAttri()
   * @generated
   */
  EAttribute getAttri_Datatype();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.asomemodel.Attri#getMultiplicity <em>Multiplicity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Multiplicity</em>'.
   * @see org.xtext.asomemodel.Attri#getMultiplicity()
   * @see #getAttri()
   * @generated
   */
  EReference getAttri_Multiplicity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.asomemodel.Attri#getOrder <em>Order</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Order</em>'.
   * @see org.xtext.asomemodel.Attri#getOrder()
   * @see #getAttri()
   * @generated
   */
  EAttribute getAttri_Order();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AsomemodelFactory getAsomemodelFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.asomemodel.impl.AsomemodelImpl <em>Asomemodel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.asomemodel.impl.AsomemodelImpl
     * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getAsomemodel()
     * @generated
     */
    EClass ASOMEMODEL = eINSTANCE.getAsomemodel();

    /**
     * The meta object literal for the '{@link org.xtext.asomemodel.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.asomemodel.impl.ModelImpl
     * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Repositoryservice</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__REPOSITORYSERVICE = eINSTANCE.getModel_Repositoryservice();

    /**
     * The meta object literal for the '<em><b>Domaininterface</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DOMAININTERFACE = eINSTANCE.getModel_Domaininterface();

    /**
     * The meta object literal for the '{@link org.xtext.asomemodel.impl.RepositoryServiceImpl <em>Repository Service</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.asomemodel.impl.RepositoryServiceImpl
     * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getRepositoryService()
     * @generated
     */
    EClass REPOSITORY_SERVICE = eINSTANCE.getRepositoryService();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REPOSITORY_SERVICE__NAME = eINSTANCE.getRepositoryService_Name();

    /**
     * The meta object literal for the '<em><b>Dataport</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REPOSITORY_SERVICE__DATAPORT = eINSTANCE.getRepositoryService_Dataport();

    /**
     * The meta object literal for the '{@link org.xtext.asomemodel.impl.DomainInterfaceImpl <em>Domain Interface</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.asomemodel.impl.DomainInterfaceImpl
     * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getDomainInterface()
     * @generated
     */
    EClass DOMAIN_INTERFACE = eINSTANCE.getDomainInterface();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOMAIN_INTERFACE__NAME = eINSTANCE.getDomainInterface_Name();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAIN_INTERFACE__ELEMENT = eINSTANCE.getDomainInterface_Element();

    /**
     * The meta object literal for the '{@link org.xtext.asomemodel.impl.DataPortImpl <em>Data Port</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.asomemodel.impl.DataPortImpl
     * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getDataPort()
     * @generated
     */
    EClass DATA_PORT = eINSTANCE.getDataPort();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_PORT__NAME = eINSTANCE.getDataPort_Name();

    /**
     * The meta object literal for the '<em><b>Cross Model</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_PORT__CROSS_MODEL = eINSTANCE.getDataPort_CrossModel();

    /**
     * The meta object literal for the '<em><b>Cross Interface</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_PORT__CROSS_INTERFACE = eINSTANCE.getDataPort_CrossInterface();

    /**
     * The meta object literal for the '{@link org.xtext.asomemodel.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.asomemodel.impl.ElementImpl
     * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '<em><b>Attri</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__ATTRI = eINSTANCE.getElement_Attri();

    /**
     * The meta object literal for the '{@link org.xtext.asomemodel.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.asomemodel.impl.EntityImpl
     * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Multiplicity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__MULTIPLICITY = eINSTANCE.getEntity_Multiplicity();

    /**
     * The meta object literal for the '{@link org.xtext.asomemodel.impl.MultiplicityImpl <em>Multiplicity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.asomemodel.impl.MultiplicityImpl
     * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getMultiplicity()
     * @generated
     */
    EClass MULTIPLICITY = eINSTANCE.getMultiplicity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICITY__NAME = eINSTANCE.getMultiplicity_Name();

    /**
     * The meta object literal for the '{@link org.xtext.asomemodel.impl.ValueObjectImpl <em>Value Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.asomemodel.impl.ValueObjectImpl
     * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getValueObject()
     * @generated
     */
    EClass VALUE_OBJECT = eINSTANCE.getValueObject();

    /**
     * The meta object literal for the '{@link org.xtext.asomemodel.impl.AttriImpl <em>Attri</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.asomemodel.impl.AttriImpl
     * @see org.xtext.asomemodel.impl.AsomemodelPackageImpl#getAttri()
     * @generated
     */
    EClass ATTRI = eINSTANCE.getAttri();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRI__NAME = eINSTANCE.getAttri_Name();

    /**
     * The meta object literal for the '<em><b>Cross Model</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRI__CROSS_MODEL = eINSTANCE.getAttri_CrossModel();

    /**
     * The meta object literal for the '<em><b>Cross Interface</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRI__CROSS_INTERFACE = eINSTANCE.getAttri_CrossInterface();

    /**
     * The meta object literal for the '<em><b>Datatype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRI__DATATYPE = eINSTANCE.getAttri_Datatype();

    /**
     * The meta object literal for the '<em><b>Multiplicity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRI__MULTIPLICITY = eINSTANCE.getAttri_Multiplicity();

    /**
     * The meta object literal for the '<em><b>Order</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRI__ORDER = eINSTANCE.getAttri_Order();

  }

} //AsomemodelPackage
