/**
 * generated by Xtext 2.10.0
 */
package org.xtext.asomemodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Asomemodel</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.asomemodel.AsomemodelPackage#getAsomemodel()
 * @model
 * @generated
 */
public interface Asomemodel extends EObject
{
} // Asomemodel
