/**
 * generated by Xtext 2.10.0
 */
package org.xtext.asomemodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.asomemodel.Model#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.asomemodel.Model#getRepositoryservice <em>Repositoryservice</em>}</li>
 *   <li>{@link org.xtext.asomemodel.Model#getDomaininterface <em>Domaininterface</em>}</li>
 * </ul>
 *
 * @see org.xtext.asomemodel.AsomemodelPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends Asomemodel
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.asomemodel.AsomemodelPackage#getModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.asomemodel.Model#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Repositoryservice</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Repositoryservice</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repositoryservice</em>' containment reference.
   * @see #setRepositoryservice(RepositoryService)
   * @see org.xtext.asomemodel.AsomemodelPackage#getModel_Repositoryservice()
   * @model containment="true"
   * @generated
   */
  RepositoryService getRepositoryservice();

  /**
   * Sets the value of the '{@link org.xtext.asomemodel.Model#getRepositoryservice <em>Repositoryservice</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Repositoryservice</em>' containment reference.
   * @see #getRepositoryservice()
   * @generated
   */
  void setRepositoryservice(RepositoryService value);

  /**
   * Returns the value of the '<em><b>Domaininterface</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Domaininterface</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domaininterface</em>' containment reference.
   * @see #setDomaininterface(DomainInterface)
   * @see org.xtext.asomemodel.AsomemodelPackage#getModel_Domaininterface()
   * @model containment="true"
   * @generated
   */
  DomainInterface getDomaininterface();

  /**
   * Sets the value of the '{@link org.xtext.asomemodel.Model#getDomaininterface <em>Domaininterface</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Domaininterface</em>' containment reference.
   * @see #getDomaininterface()
   * @generated
   */
  void setDomaininterface(DomainInterface value);

} // Model
