/**
 * generated by Xtext 2.10.0
 */
package org.xtext.asomemodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Repository Service</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.asomemodel.RepositoryService#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.asomemodel.RepositoryService#getDataport <em>Dataport</em>}</li>
 * </ul>
 *
 * @see org.xtext.asomemodel.AsomemodelPackage#getRepositoryService()
 * @model
 * @generated
 */
public interface RepositoryService extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.asomemodel.AsomemodelPackage#getRepositoryService_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.asomemodel.RepositoryService#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Dataport</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dataport</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dataport</em>' containment reference.
   * @see #setDataport(DataPort)
   * @see org.xtext.asomemodel.AsomemodelPackage#getRepositoryService_Dataport()
   * @model containment="true"
   * @generated
   */
  DataPort getDataport();

  /**
   * Sets the value of the '{@link org.xtext.asomemodel.RepositoryService#getDataport <em>Dataport</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dataport</em>' containment reference.
   * @see #getDataport()
   * @generated
   */
  void setDataport(DataPort value);

} // RepositoryService
