/**
 * generated by Xtext 2.10.0
 */
package org.xtext.asomemodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value Object</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.asomemodel.AsomemodelPackage#getValueObject()
 * @model
 * @generated
 */
public interface ValueObject extends Element
{
} // ValueObject
