/**
 * generated by Xtext 2.10.0
 */
package org.xtext;

import org.xtext.AsomemodelStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AsomemodelStandaloneSetup extends AsomemodelStandaloneSetupGenerated {
  public static void doSetup() {
    AsomemodelStandaloneSetup _asomemodelStandaloneSetup = new AsomemodelStandaloneSetup();
    _asomemodelStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
