/**
 * generated by Xtext 2.10.0
 */
package org.xtext.asomemodel.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.asomemodel.Asomemodel;
import org.xtext.asomemodel.AsomemodelPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Asomemodel</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AsomemodelImpl extends MinimalEObjectImpl.Container implements Asomemodel
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AsomemodelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsomemodelPackage.Literals.ASOMEMODEL;
  }

} //AsomemodelImpl
