/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.amodel.ui.internal.AmodelActivator;

public class AsomemodelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AmodelActivator.getInstance().getInjector("org.xtext.Asomemodel");
	}

}
